"""empty message

Revision ID: 133cecb9a325
Revises: 1a6bbfc6306a
Create Date: 2022-06-27 00:27:56.203372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133cecb9a325'
down_revision = '1a6bbfc6306a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declined_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declined_quotes_author'), 'declined_quotes', ['author'], unique=False)
    op.create_index(op.f('ix_declined_quotes_name'), 'declined_quotes', ['name'], unique=False)
    op.create_index(op.f('ix_declined_quotes_quote'), 'declined_quotes', ['quote'], unique=False)
    op.create_index(op.f('ix_declined_quotes_source'), 'declined_quotes', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declined_quotes_source'), table_name='declined_quotes')
    op.drop_index(op.f('ix_declined_quotes_quote'), table_name='declined_quotes')
    op.drop_index(op.f('ix_declined_quotes_name'), table_name='declined_quotes')
    op.drop_index(op.f('ix_declined_quotes_author'), table_name='declined_quotes')
    op.drop_table('declined_quotes')
    # ### end Alembic commands ###
