"""users table

Revision ID: 570312a09f63
Revises: 133cecb9a325
Create Date: 2022-08-03 20:21:25.770686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570312a09f63'
down_revision = '133cecb9a325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=True),
    sa.Column('current_logged_in', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('quotes', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'user_id')
    op.drop_column('quotes', 'stage')
    op.drop_table('users')
    # ### end Alembic commands ###
