"""quotesApproved

Revision ID: 9d6a9b0aed73
Revises: 5edf9744a8fb
Create Date: 2022-06-25 15:26:08.660767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6a9b0aed73'
down_revision = '5edf9744a8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_author', table_name='quotes')
    op.drop_index('ix_quotes_name', table_name='quotes')
    op.drop_index('ix_quotes_quote', table_name='quotes')
    op.drop_index('ix_quotes_source', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_approved_quotes_author', table_name='approved_quotes')
    op.drop_index('ix_approved_quotes_name', table_name='approved_quotes')
    op.drop_index('ix_approved_quotes_quote', table_name='approved_quotes')
    op.drop_index('ix_approved_quotes_source', table_name='approved_quotes')
    op.drop_table('approved_quotes')
    op.drop_index('ix_quotes_to_approve_author', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_name', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_quote', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_source', table_name='quotes_to_approve')
    op.drop_table('quotes_to_approve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_to_approve',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_to_approve_source', 'quotes_to_approve', ['source'], unique=False)
    op.create_index('ix_quotes_to_approve_quote', 'quotes_to_approve', ['quote'], unique=False)
    op.create_index('ix_quotes_to_approve_name', 'quotes_to_approve', ['name'], unique=False)
    op.create_index('ix_quotes_to_approve_author', 'quotes_to_approve', ['author'], unique=False)
    op.create_table('approved_quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approved_quotes_source', 'approved_quotes', ['source'], unique=False)
    op.create_index('ix_approved_quotes_quote', 'approved_quotes', ['quote'], unique=False)
    op.create_index('ix_approved_quotes_name', 'approved_quotes', ['name'], unique=False)
    op.create_index('ix_approved_quotes_author', 'approved_quotes', ['author'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_source', 'quotes', ['source'], unique=False)
    op.create_index('ix_quotes_quote', 'quotes', ['quote'], unique=False)
    op.create_index('ix_quotes_name', 'quotes', ['name'], unique=False)
    op.create_index('ix_quotes_author', 'quotes', ['author'], unique=False)
    # ### end Alembic commands ###
