"""quotes to app

Revision ID: a7b87f40e38a
Revises: f258944d117f
Create Date: 2022-06-25 02:16:41.481990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b87f40e38a'
down_revision = 'f258944d117f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_to_approve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_to_approve_author'), 'quotes_to_approve', ['author'], unique=True)
    op.create_index(op.f('ix_quotes_to_approve_name'), 'quotes_to_approve', ['name'], unique=True)
    op.create_index(op.f('ix_quotes_to_approve_quote'), 'quotes_to_approve', ['quote'], unique=True)
    op.create_index(op.f('ix_quotes_to_approve_source'), 'quotes_to_approve', ['source'], unique=True)
    op.drop_index('ix_quotes_like_count', table_name='quotes')
    op.drop_index('ix_quotes_timestamp', table_name='quotes')
    op.drop_column('quotes', 'timestamp')
    op.drop_column('quotes', 'like_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('like_count', sa.INTEGER(), nullable=True))
    op.add_column('quotes', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_quotes_timestamp', 'quotes', ['timestamp'], unique=False)
    op.create_index('ix_quotes_like_count', 'quotes', ['like_count'], unique=False)
    op.drop_index(op.f('ix_quotes_to_approve_source'), table_name='quotes_to_approve')
    op.drop_index(op.f('ix_quotes_to_approve_quote'), table_name='quotes_to_approve')
    op.drop_index(op.f('ix_quotes_to_approve_name'), table_name='quotes_to_approve')
    op.drop_index(op.f('ix_quotes_to_approve_author'), table_name='quotes_to_approve')
    op.drop_table('quotes_to_approve')
    # ### end Alembic commands ###
