"""quotes to app

Revision ID: d404433f0210
Revises: a7b87f40e38a
Create Date: 2022-06-25 02:30:04.050815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd404433f0210'
down_revision = 'a7b87f40e38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_author', table_name='quotes')
    op.drop_index('ix_quotes_name', table_name='quotes')
    op.drop_index('ix_quotes_quote', table_name='quotes')
    op.drop_index('ix_quotes_source', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_quotes_to_approve_author', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_name', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_quote', table_name='quotes_to_approve')
    op.drop_index('ix_quotes_to_approve_source', table_name='quotes_to_approve')
    op.drop_table('quotes_to_approve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_to_approve',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_to_approve_source', 'quotes_to_approve', ['source'], unique=False)
    op.create_index('ix_quotes_to_approve_quote', 'quotes_to_approve', ['quote'], unique=False)
    op.create_index('ix_quotes_to_approve_name', 'quotes_to_approve', ['name'], unique=False)
    op.create_index('ix_quotes_to_approve_author', 'quotes_to_approve', ['author'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_source', 'quotes', ['source'], unique=False)
    op.create_index('ix_quotes_quote', 'quotes', ['quote'], unique=False)
    op.create_index('ix_quotes_name', 'quotes', ['name'], unique=False)
    op.create_index('ix_quotes_author', 'quotes', ['author'], unique=False)
    # ### end Alembic commands ###
