"""first quote

Revision ID: f258944d117f
Revises: 
Create Date: 2022-06-22 23:17:39.761476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f258944d117f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=True)
    op.create_index(op.f('ix_quotes_like_count'), 'quotes', ['like_count'], unique=True)
    op.create_index(op.f('ix_quotes_name'), 'quotes', ['name'], unique=True)
    op.create_index(op.f('ix_quotes_quote'), 'quotes', ['quote'], unique=True)
    op.create_index(op.f('ix_quotes_source'), 'quotes', ['source'], unique=True)
    op.create_index(op.f('ix_quotes_timestamp'), 'quotes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_timestamp'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_source'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_name'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_like_count'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
